### ISSUE TITLE
isFirstItemVisible()  Not natural.

### ISSUE THREAD

**Issue by chodongsuk** [emmasuzuki/QuickReturnListView#1]
private boolean isFirstItemVisible() {
return mAbsListView.getFirstVisiblePosition() < 0;
}
The first position can scroll up to the return to the first view is there is abslistview I get to arise as moving back ??

**Comment by emmasuzuki** [comment]
I removed the `isFirstItemVisible()` method and made quick return shown always when first item is visible.
