### ISSUE TITLE
QuickReturnListView  in DrawerLayout

### ISSUE THREAD

**Issue by AndroidFa** [emmasuzuki/QuickReturnListView#2]
If QuickReturnListView  in DrawerLayout ,  ListView is not  show FirstItem!

**Comment by emmasuzuki** [comment]
Hi, @AndroidFa .  Thanks for checking out this repo. 

This repo is old and my apology on not updating this for a long time. 
Though, good news is that Android now has built-in QuickReturn and that works way better and feature rich.  
 
Please checkout `CoordinatorLayout` and `app:layout_behavior`.  There are tons of tutorials.  

Thanks to your question and new built-in, I will deprecate this repo.

**Comment by AndroidFa** [comment]
Thank you for your reply.I have found the solution.
